const START_PARSER = 'START-PARSER';
const CHANGE_PARSER_STARTUP_STATE = 'CHANGE-PARSER-STARTUP-STATE';
const CHANGE_PARSER_READINESS_STATE = 'CHANGE-PARSER-READINESS-STATE';
const GET_PARSER_STATE = 'GET-PARSER-STATE';
const CHANGE_BUTTON_DISABLED_STATE = 'CHANGE-BUTTON-DISABLED-STATE';
const SAVE_BOOKS = 'SAVE-BOOKS';

export {
  START_PARSER, CHANGE_PARSER_STARTUP_STATE, SAVE_BOOKS,
  CHANGE_PARSER_READINESS_STATE, GET_PARSER_STATE, CHANGE_BUTTON_DISABLED_STATE
};
