const START_PARSER = 'START-PARSER';
const CHANGE_PARSER_STARTUP_STATE = 'CHANGE-PARSER-STARTUP-STATE';
const CHANGE_PARSER_READINESS_STATE = 'CHANGE-PARSER-READINESS-STATE';
const GET_PARSER_STATE = 'GET-PARSER-STATE';

export { START_PARSER, CHANGE_PARSER_STARTUP_STATE, CHANGE_PARSER_READINESS_STATE, GET_PARSER_STATE };
